[package]
name = "rust_bridgebot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
dotenv = "0.15.0"
serenity = "0.11.5"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
diesel = { version = "2.1.3", features = ["postgres"] }
