[package]
name = "rust_bridgebot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
serenity = "0.11.5"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
diesel = { version = "2.1.4", features = ["postgres"] }
log = "0.4"
env_logger = "0.10"
